# Copyright 2025 The go-yaml Project Contributors
# SPDX-License-Identifier: Apache-2.0

version: 2

updates:
- package-ecosystem: gomod
  directory: /  # Location of package manifests
  schedule:
    interval: weekly

- package-ecosystem: github-actions
  directory: /
  groups:
    actions:
      patterns: ['*']
  schedule:
    interval: weekly
