# Copyright 2025 The go-yaml Project Contributors
# SPDX-License-Identifier: Apache-2.0

name: Commit Message Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: read-all

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        fetch-depth: 0  # Fetch all history to ensure all SHAs are available
        persist-credentials: false

    - name: Check PR Commits
      run:
        util/check-commit-messages
        ${{ github.event.pull_request.base.sha }}..${{
            github.event.pull_request.head.sha }}
