name: Commit Message Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: read-all

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      with:
        fetch-depth: 0  # Fetch all history to ensure all SHAs are available
        persist-credentials: false
    - name: Check PR Commits
      run:
        util/check-commit-messages.sh
        ${{ github.event.pull_request.base.sha }}..${{
            github.event.pull_request.head.sha }}
