name: Commit Message Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions: read-all

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      with:
        fetch-depth: 0  # Fetch all history to ensure all SHAs are available
        persist-credentials: false

    - name: Check PR Commits
      run:
        util/check-commit-messages
        ${{ github.event.pull_request.base.sha }}..${{
            github.event.pull_request.head.sha }}
