# Copyright 2025 The go-yaml Project Contributors
# SPDX-License-Identifier: Apache-2.0

name: Forbid Merge Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions: read-all

jobs:
  forbid-merge-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Run Forbid Merge Commits Action
      # yamllint disable-line rule:line-length
      uses: motlin/forbid-merge-commits-action@d508a7b3148cc98b51a5f062d60396f09f5bc269  # v1.0.7
      with:
        fail-on-merge-commits: true
